ctype: "median"
conditions:
  main:
    - "债券类型 = '可转债'"
    - "转换价值>80"
    - "转换价值<=100"
  sort: null
  sort_type: ""
  limit: -1
  ratio_total:
    - "债券类型 = '可转债'"
column: "转股溢价率(%)"
file_name: "80-100平价的估值"
file_name_format: true
column_name:
  ratio:
    - "日期"
    - "纯债到期收益率 > 3% 的转债个数"
    - "转债总数"
  median:
    - "日期"
    - "中位数"
  avg:
    - "日期"
    - "平均数"
  max:
    - "日期"
    - "最大值"
  min:
    - "日期"
    - "最小值"
  std_0:
    - "日期"
    - "有偏样本标准差"
  std_1:
    - "日期"
    - "无偏样本标准差"
  check:
    - "数据表"
    - "缺失数据"
