name: Push to Gitee

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Black list
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/cuxt
          dst: gitee/PinHsin
          dst_key: ${{ secrets.SSH_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_API }}
          static_list: "convertible_bond_script"
